README.md
main.ts
manifest.json
package.json

Added file context menu

---

src/flashcard-modal.ts
src/main.ts
src/settings.ts
styles.css

Added settings for burying of related cards & easy bonus.
Put settings into different categories.

Cleaned up settings

---

src/flashcard-modal.ts
src/main.ts
src/settings.ts
styles.css

1. Reset card's progress => #33
2. Burying of related cloze cards until next review session
3. Proper detach of right sidebar

Reset card's progress, burying related cloze cards, etc

---

src/flashcard-modal.ts
src/main.ts

Add flashcards count to statusbar, bugs fix

Add flashcards count to statusbar, bugs fix

---

src/declarations.d.ts
src/flashcard-modal.ts
src/main.ts
src/sched.ts
src/settings.ts
src/types.ts
styles.css

- Some refactor & bug fixes
- Related issues:
- Decks: #30 
- Make flashcards view scrollable: #46

Decks, make flashcards view scrollable

---

src/constants.ts

Fix issue with horizontal rules during notes review

---

src/flashcard-modal.ts
src/main.ts

Change date format to YYYY-MM-DD

---

package.json
src/flashcard-modal.ts
styles.css

Fixes #52.
Working functionality.

Fixes for better mobile UI/UX

---

src/main.ts

Shortcut for review flashcards

---

src/flashcard-modal.ts
src/main.ts
src/sched.ts

Use month(s) & year(s) when intervals get too big

---

src/flashcard-modal.ts
src/main.ts
src/sched.ts
src/settings.ts
src/types.ts

Maximum interval option

---

src/main.ts
src/settings.ts
src/types.ts

Update plugin settings

---

src/settings.ts
src/sidebar.ts
src/types.ts

Limit on number of days to display on right panel

---

src/constants.ts
src/flashcard-modal.ts
src/settings.ts
src/types.ts

Indentation to be preserved while making flashcard

---

src/main.ts

fix review flashcards command

---

src/main.ts
src/settings.ts
src/types.ts

disable cloze cards option

---

src/flashcard-modal.ts

Fix reset progress NaN bug

---

src/flashcard-modal.ts
src/utils.ts

Fix dollar signs replacement

---

src/settings.ts

Settings: split tags with newlines and spaces

---

src/flashcard-modal.ts
src/settings.ts
src/types.ts

showFileNameInFileLink option

---

src/flashcard-modal.ts
src/main.ts
src/sched.ts
src/settings.ts
src/sidebar.ts
src/types.ts
styles.css

Nested decks feature

---

src/constants.ts

fix parsing of http(s) image links

---

src/flashcard-modal.ts
src/main.ts
src/sched.ts
src/types.ts

Boost cards after delay.

---

src/flashcard-modal.ts
src/main.ts
src/sched.ts

load balancing

---

src/flashcard-modal.ts

fix deck counts going into negatives

---

src/main.ts

show folders based on the presence of flashcards instead of files

---

styles.css

fix CSS on light themes

---

src/flashcard-modal.ts
src/main.ts
src/utils.ts

better burying of cards

---

src/flashcard-modal.ts

fix deck transition behavior

---

src/main.ts
src/sidebar.ts
src/stats-modal.ts

Requires Obsidian charts plugin.

Cards forecast stats

---

src/main.ts

Parse card only once

---

src/main.ts

fix bug when parsing nonexistent images

---

src/constants.ts
src/flashcard-modal.ts
src/main.ts
src/settings.ts
src/types.ts

resize image, large screen mode

---

src/flashcard-modal.ts
src/settings.ts
src/types.ts

Randomize card order option

---

src/flashcard-modal.ts
src/main.ts
src/scheduling.ts

Go to flashcard position after clicking open file

---

src/stats-modal.ts
src/utils.ts

Fix statistics view - accumulate overdue cards, linearity

---

README.md
src/flashcard-modal.ts
src/main.ts
src/scheduling.ts
src/settings.ts

Caching & settings debounce fix

---

README.md
src/constants.ts
src/flashcard-modal.ts
src/logger.ts
src/main.ts
src/scheduling.ts
src/settings.ts
src/utils.ts

Generalize flashcards processing & logging

---

.gitignore

Small recommendation, but for those of working with .vscode, it is nice to have this folder excluded.
Thank you.

Added for those working with VSCODE

---

src/flashcard-modal.ts

I removed this from the original code, but have now returned it. the positioning of the cursor is a great feature.

Returned cursor position  on "open file" or "Edit later"

---

src/flashcard-modal.ts
src/lang/locale/en.ts
src/main.ts
styles.css

A (very rough) implementation of #279.
This might not be very scalable or good code, but it's been working for me. If nothing else, it gives a jumping-off point.

Cram Flashcards

---

src/flashcard-modal.ts

Fixes PR #289 to display mp3 and webm audio so they can be played

Updated to display mp3 and webm audio on flashcards

---

src/lang/locale/en.ts

I believe we changed the term used in the flashcard review.
This will update the text in the settings screen.

Open file was changed to "Edit Later"

---

src/lang/locale/ja.ts

Hi, thanks for developing this SRS plugin.
I've completed Japanese translation! (I'm the first translator?😎)
Please merge this PR.

ja: added Japanese translation

---

jest.config.js
src/lang/helpers.ts
src/main.ts
src/scheduling.ts
src/settings.ts
src/stats-modal.ts
tests/__mocks__/obsidian.js
tests/lang/helpers.test.ts
tests/scheduling.test.ts

Builds on top of #315 ... so far just a single unit test to see if it works :)

Scheduling unit tests

---

src/flashcard-modal.ts

After grumbling a bit about the Obsidian API, I managed to implement support for transclusions in flash cards. I am not familiar with Typescript or the toolchain, but this worked well for me. It can definitely do with some cleanup, is there something else I need to do? (implements #216)

transclusions initial implementation

---

src/flashcard-modal.tsx
tests/__mocks__/obsidian.js

Fix first time random card selection

---

src/flashcard-modal.tsx
src/lang/locale/en.ts
src/settings.tsx
yarn.lock

Regenerate yarn.lock file

---

styles.css

Make flashcard text selectable

---

src/constants.ts

Update flashcards image formats

---

docs/en/flashcards.md

Update the document to avoid confusion about the sibling behaviour of reversed card
See https://github.com/st3v3nmw/obsidian-spaced-repetition/issues/698

doc: update note about the reversed card

---

src/lang/locale/pt-br.ts

Updated Brazilian Portuguese for missing items.
Corrected some misspelled words and improved the grammar.

Update pt-br.ts for Brazilian Portuguese translation

---

src/Card.ts

when card has dummy schedule, this isNew return false, but should be true. current is 
```ts
get isNew(): boolean {
return !this.hasSchedule;
}
```
change to
```ts
get isNew(): boolean {
return !this.hasSchedule || this.scheduleInfo.isDummyScheduleForNewCard();
}
```

fix card isNew

---

.github/workflows/e2e.yml
.github/workflows/pr.yml
.github/workflows/release.yml
package.json

chore: fix package manager issue in CI

---

src/gui/review-queue-list-view.tsx

as discussed in #1060, to fix conflict, reopen it in this pr.

fix: sidebar note display

---

package.json
pnpm-lock.yaml

- removes caret from pnpm package manager definition
- specifiy minimum pnpm version
-fixes #1091

fix: remove caret from package manager definition

---

src/gui/flashcard-review-view.tsx

fix(ui): render markdown content for questions in nested lists

---

src/core.ts
src/gui/review-queue-list-view.tsx
src/gui/sidebar.tsx
src/gui/statistics.tsx
src/main.ts
src/next-note-review-handler.ts
tests/unit/helpers/unit-test-core.ts

Fixes https://github.com/st3v3nmw/obsidian-spaced-repetition/discussions/1135.

fix(sidebar): duplicate icons & reviewQueueView undefined exception

---

src/gui/settings.tsx
src/lang/locale/ar.ts
src/lang/locale/cz.ts
src/lang/locale/de.ts
src/lang/locale/en.ts
src/lang/locale/es.ts
src/lang/locale/fr.ts
src/lang/locale/it.ts
src/lang/locale/ja.ts
src/lang/locale/ko.ts
src/lang/locale/pl.ts
src/lang/locale/pt-br.ts
src/lang/locale/ru.ts
src/lang/locale/tr.ts
src/lang/locale/zh-cn.ts
src/lang/locale/zh-tw.ts

Fix [[Bug]: Confusing Cloze Pattern Config #1155](https://github.com/st3v3nmw/obsidian-spaced-repetition/issues/1155)

fix: Add description to cloze settings
