- src/flashcard-modal.ts
- src/main.ts
- src/types.ts
This I think fixes the issue I brought up in https://github.com/st3v3nmw/obsidian-spaced-repetition/pull/73#issuecomment-845484017
I'm not sure where else the original back and front text could be used. I don't think Cloze cards will run into this same issue.
> store original front and back text to put back after review

- src/flashcard-modal.ts
- src/settings.ts
- src/types.ts
I needed to be able to change this so that on iPad it's prettier and doesn't blow up images to fill up the whole screen. 
I did remove the largeDisplayMode setting as that's now doable by just making width and height 100%. That is a breaking change, but I'm not sure how much it was actually used. It's an easy fix on the user's side to just adjust both to 100%. Thoughts?
> Allow flashcard height and width to be customizable

- src/lang/locale/en.ts
- src/main.ts
- src/settings.ts
Partially fixes #13 (added only for notes, not for flashcards --- I never used them so don't have any for testing)
> Add option to ignore folders in note review

- src/flashcard-modal.ts
- src/lang/locale/en.ts
Make the "open file" open the file in the background for editing after the SR session ends. Thus, move the user to the next flashcard for review
This would  be an alternative solution  for the issue: https://github.com/st3v3nmw/obsidian-spaced-repetition/issues/269
> Change "Open file"  to "Edit later"

- src/main.ts
This fixes the issue of defineing a parent tag as a review tag and the plugin using the full tag which can clutter things up dramatically. e.g.
in the setting I have  #reference as a tag to review 
but in the UI the plugin uses all the sibling tags like so 
This fix uses the tags from the user preference in the UI to get this:
Let me know your thoughts.
> Using tags from User Preferences and not their full name that includes the sibling

- src/review-deck.ts
- src/sidebar.ts
When the sidebar was redrawn, the deck and scheduled notes folders would return to the default expanded/collapsed setting. This makes sure they reflect the previous state when redrawing.
Also fix setting last reviewed deck when clicking on a note in the sidebar. Now when a note is clicked on the sidebar, the last reviewed deck is set to the selected note's deck.
This is the first fix that came to mind. It might not be the best way to do it but it has been working for me.
> Fix collapsed/expanded states when redrawing the sidebar

- src/lang/locale/de.ts
- src/lang/locale/en.ts
- src/stats-modal.ts
Translation is complete.
I haven't viewed the translation live in obsidian yet though, but I believe it should look fine.
In stats-modal.ts, the texts `New`, `Young` and `Mature` were hardcoded. I added translation keys for them and translations for english and german. 
Relates to: https://github.com/st3v3nmw/obsidian-spaced-repetition/issues/282
> Added translations DE

- src/lang/locale/en.ts
I just downloaded the plugin and noticed this mistake in the English lang file.
It's a small change, so it should be an easy merge.
Thank you for making this plugin :)
> Correct notes(s) to note(s) in en.ts lang file

- jest.config.js
- src/lang/helpers.ts
- src/main.ts
- src/scheduling.ts
- src/settings.ts
- src/stats-modal.ts
- tests/__mocks__/obsidian.js
- tests/lang/helpers.test.ts
While we can't change the existing Obsidian API that sometimes extends string with new methods, it's not necessary to extend string when we only need interpolation when calling t for translated strings...
This PR makes it a small bit easier to test scheduling.ts by avoiding the need to provide a global interpolate function for every string.
Provided some unit tests for translation and interpolation, just to make sure it continued to work as expected.
> Changing interpolate to an optional arg of t

- src/parser.ts
as seen in #349 
code checking for the comment end checks on the next line rather than the same line 
This causes some causing parsing issues.
> [Bug fix] for HTML Comment parsing

- src/parser.ts
Markdown has two code fences syntaxes: multiple backticks and multiple tildes. It also supports nested code fences. For example
`````markdown
An admonition:
````ad-note
```git
+ print("hello")
- print("world")
```
~~~python
print("hello world")
~~~
````
`````
This pull request makes the plugin support the more general Markdown code fences syntax.
> fix: handle code fences better

- src/constants.ts
Was pulling my hair out trying to figure out why an audio file wouldn't embed -- turns out ogg wasn't supported! I modified the constant in the exported .js file and now it works just fine.
> Add "ogg" as supported audio file format

- src/flashcard-modal.tsx
- src/main.ts
I find it will be much more convenient if the deck list can remember which entry the user have clicked before exiting the window. So I implemented this feature and have tested for several monthes. It works well so I do PR to the upstream.
> [feat] add modal history feature

- src/parser.ts
This replaces all crlf line break to lf line break when parsing card, in this way, line separator with linebreak "\r\n" can also be detected
> Replace crlf to lf on card parse

- src/constants.ts
Addresses #527 by changing `SCHEDULING_INFO_REGEX` to only match to next `---`.
> Prevent regex from matching to last --- in file

- src/flashcard-modal.tsx
This prevents pressing \<Space\> from activating any focused button.
For example, if I press the skip button, the button will become focused and the next flashcard shows up. Then in the next flashcard, when I want to press \<Space\> to reveal the answer, the focused skip button is also activated because the `keydown` event is not consumed, leading to the flashcard being skipped instead of having its answer revealed like I intended.
> Consume keyboard event in flashcard modal

- src/flashcard-modal.tsx
Closes #655
The problem is that the initial value of `collapsed` was being set to the `shouldBeInitiallyExpanded` config value, even though these booleans should be opposite (collapsed vs. expanded).
Because the initial UI was set from `shouldBeInitiallyExpanded`, but the callback to the click event checked `collapsed`, the first click would make no visual change, but merely set the `collapsed` variable to be correct, and the second click would work as expected.
Technically only the  change on line `846` is necessary, but the other two changes prevent the same visual confusion from occurring in the future by ensuring that that the UI and `collapsed` are in sync.
> Fix issue requiring collapseIcon to be clicked twice to expand/collapsed deck tree

- src/lang/locale/en.ts
Issue:
After adjust max interval, the user may confuse with the unit it behinds. (days, years, or something else.)
Solution:
A simple practical solution could be add unit description in title.
There is no reason to change variables and name inside.
> show MAX_INTERVAL unit in title

- .github/workflows/stale.yml
- docs/changelog.md
Issue/PR marked as stale after 1 year of inactivity, closed if it sees no activity for 30 days.
> Close very old issues (>= 1 year)

- src/flashcard-modal.tsx
As discussed in #630 , the skip after modifying a card is not a good design choice. I removed the line.
> remove skip after modifying card text

- src/parser.ts
- tests/unit/parser.test.ts
Fixed issue mentioned here: #690. 
**Changes:** 
- Defined `currentLine` variable in the beginning of the main cycle in `src/parser.ts` 
- Used `trim()` to remove the extra spaces when appending `cardText`
- Used `trim()` to clean the line before comparing with separator symbol
> Remove the spaces before and after the question marks in the multi-line basic flashcards

- src/util/MultiLineTextFinder.ts
- src/util/utils.ts
- tests/unit/FlashcardReviewSequencer.test.ts
- tests/unit/util/utils.test.ts
Fixes issue https://github.com/st3v3nmw/obsidian-spaced-repetition/issues/766
Although not mentioned in that issue note, the bug also caused a problem with cards with the "$$" whilst being edited within card modal. The bug was in code used in both cases, and so has been fixed for both.
> Multi-line tag ('$$') converted to single-line ('$') after card reviewed

- src/util/MultiLineTextFinder.ts
> [BUG] Static method findAndReplace leads to failure if the lineNo is 0 instead of null #828

- src/gui/DeckListView.tsx
Small follow-up on #899
I think that we should show the "most useful" counts first. When reviewing, it's best if users see the due & new cards first as this makes it a bit easier to select the deck to review especially for left-to-right languages which are the vast majority of what we support. Or if they have many decks.
@KyleKlus
> style(card review modal): reorder stats containers

- src/main.ts
- src/util/utils.ts
- tests/unit/util/utils.test.ts
Fixes #969 
Implementation of better comparison 
Implementation of Unit Test
> [FIX] Folder ignore sorts all folder starting with string

- src/gui/FlashcardReviewView.tsx
- src/util/RenderMarkdownWrapper.ts
Fixes #966 
Scroll back after review card done. Required for longer cards or small screens.
> [FIX] Not scroll back to top after review

- src/gui/FlashcardModal.tsx
- styles.css
Based on the discussion in https://github.com/st3v3nmw/obsidian-spaced-repetition/discussions/990
- added CSS to make UI elements rotate when the mobile device is rotated
- made size sliders change the `max-width` and `max-height` to make them fully effective (proper full screen when width and height are at 100%)
Tested on desktop and mobile.
> FEAT-990 Mobile landscape mode + fully functional resize sliders

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/workflows/release.yml
- docs/en/contributing.md
- docs/license.md
- docs/zh/contributing.md
- mkdocs.yml
- requirements.txt
> fix: add language switcher to docs

- src/util/RenderMarkdownWrapper.ts
Fixed https://github.com/st3v3nmw/obsidian-spaced-repetition/issues/1041
In version 1.12.4 and earlier we used the deprecated Obsidian MarkdownRenderer.renderMarkdown() and we
needed to have our own method "renderTransclude()" that loaded the referenced file and rendered it.
In version 1.12.5, we started using MarkdownRenderer.render() instead, which does this automatically.
> fix: embedded notes are displayed twice, since 1.12.5

- README.md
- docs/docs/en/contributing.md
- src/lang/locale/fr.ts
- tests/unit/lang/helpers.test.ts
Changes in #1066 introduced new translation entries and removed 2, this updates the French locale to match.
Added:
- OBSIDIAN_INTEGRATION
- SHOW_STATUS_BAR
- SHOW_STATUS_BAR_DESC
- SHOW_RIBBON_ICON
- SHOW_RIBBON_ICON_DESC
- ENABLE_FILE_MENU_REVIEW_OPTIONS
- ENABLE_FILE_MENU_REVIEW_OPTIONS_DESC
Removed:
- DISABLE_FILE_MENU_REVIEW_OPTIONS
- DISABLE_FILE_MENU_REVIEW_OPTIONS_DESC
Follow up on #1080.
> update french translation

- CODE_OF_CONDUCT.md
- src/algorithms/base/srs-algorithm.ts
- src/constants.ts
- src/data-store-algorithm/data-store-algorithm.ts
- src/data-stores/base/data-store.ts
- src/parser.ts
- tests/unit/parser.test.ts
This PR:
1. Renames _close_ in the grammar to _cloze_
2. Adds test cases for parsing {{curly}} clozes
3. Fixes #1072
- Ignores 'cards' in ```block`` & `inline` codeblocks
- Adds test cases for both
4. Fixes #1077 
- When all the cloze options aren't being used, `cloze_rules` in `parser.ts` becomes empty which leads to the empty grammar rule `cloze_text` which prevents the parser from being generated. This change puts a [tombstone](https://en.wikipedia.org/wiki/Tombstone_(data_store)) `\0` instead to address this.
- Adds test cases for this
> fix: parsing code blocks & custom separators

- .github/workflows/test.yml
- package.json
- pnpm-lock.yaml
- src/gui/flashcard-review-view.tsx
- src/lang/locale/ar.ts
- src/lang/locale/cz.ts
- src/lang/locale/de.ts
- src/lang/locale/en.ts
- src/lang/locale/es.ts
- src/lang/locale/fr.ts
- src/lang/locale/it.ts
- src/lang/locale/ja.ts
- src/lang/locale/ko.ts
- src/lang/locale/pl.ts
- src/lang/locale/pt-br.ts
- src/lang/locale/ru.ts
- src/lang/locale/tr.ts
- src/lang/locale/zh-cn.ts
- src/lang/locale/zh-tw.ts
- src/settings.ts
- src/utils/utils.ts
- tests/unit/utils/utils.test.ts
This allows the user to ignore folders using glob patterns. For instance:
- `Computing/AWS/DynamoDB/*`
- `**/*.excalidraw.md`
- `Computing/**`
- `Computing/*/DynamoDB/*`
This was originally reported in https://github.com/open-spaced-repetition/obsidian-spaced-repetition-recall/issues/72 where the plugin was interpreting things inside excalidraw files as ==highlight== cloze cards. Like `==⚠  Switch to EXCALIDRAW VIEW in the MORE OPTIONS menu of this document. ⚠== You can decompress Drawing data with the command palette: 'Decompress current Excalidraw file'. For more info check in plugin settings under 'Saving'`.
> fix: ignore with glob patterns

- src/note-review-deck.ts
This patch fixes the behaviour of determining the next note to only consider notes that are due. If a note is scheduled in the future, it won't be picked up for review until it's due.
This is the same patch as #947.
Fixes #328.
> fix: Review only due notes

- src/note-review-deck.ts
The previous patch #1088 missed to change the conditional to also include only the filtered notes. With this patch, if all scheduled notes are in the future, it will choose a new note for review.
> fix: Only consider filtered notes for next note

- package.json
- pnpm-lock.yaml
- This change adds validation check for linting, formatting & test concurrently on commit
Fixes #880
> chore(git hook): add precommit-hook to handle validation checks

- src/parser.ts
- tests/unit/parser.test.ts
Fix issue reported in  https://github.com/st3v3nmw/obsidian-spaced-repetition/issues/1136.
> fix(multiline cards): the Qn should start from the immediate empty line above it

- src/parser.ts
- tests/unit/parser.test.ts
> fix: picking up of inline reversed cards

- styles.css
Changed the minimum width of the boxes, that there will fit for numbers up to 9999. Currently there only will fit if the numbers are below 999 what in my case and certainly for others too is not enough.
Old:
New:
> fix: Change Decks list card count box size

- src/main.ts
- src/question-postponement-list.ts
the logic here seemed to be half-there but maybe missed in a refactor?
the method clearIfNewDay was already implemented but not used anywhere in the codebase. the method is now called and
questionPostponementList.write now sets `buryDate` to the current date when called.
> fix(scheduler): clear buried questions on new day
